### ISSUE TITLE
Live.js hides styles in Chrome's inspector

### ISSUE THREAD

**Issue by tnorthcutt** [michael-martin/PBD-Live.js-for-WordPress#2]
See here: http://i.imgur.com/5IGqA.jpg

On the left, live.js is not loaded. On the right, it is.

**Comment by michael-martin** [comment]
Ah, I see what you mean now. This could be a bug in the Live.js script itself, but I don't really see what they could do about it even. The issue seems to be that the inspector doesn't update itself as the CSS files reload.

At the very least, I don't think there's much the WordPress implementation of it can do, other than perhaps turning the HTML refresh back on, but that effect is hateful...

**Comment by tnorthcutt** [comment]
Yeah, I figured it might be a but in live.js. However, it's not just that it doesn't update styles in the inspector - it doesn't even show some of them to begin with, if you start from a fresh page load. Odd behavior.

**Comment by michael-martin** [comment]
Hmmm, very. Could the first refresh happen before the inspector has time to populate itself? (I'd have thought not, given how fast the page itself renders the CSS)
